#Hugo configuration
title = "wqedsf wer"
baseURL = "https:\/\/wer.cdgvfd.dfsdf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
